# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export DOTFILES="$HOME/.dotfiles"
export ZSH="$HOME/.oh-my-zsh"

# History
HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/.zsh_history
HIST_STAMPS="dd/mm/yyyy"

ZSH_THEME="powerlevel10k/powerlevel10k"
COMPLETION_WAITING_DOTS="true"

plugins=(
    git
    zsh-z
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/aliases
source $DOTFILES/zsh/opts

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# load powerline10k config, previously configured
[[ ! -f $DOTFILES/zsh/.p10k.zsh ]] || source $DOTFILES/zsh/.p10k.zsh