# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export DOTFILES="$HOME/.dotfiles"
export ZSH="$HOME/.oh-my-zsh"

. $DOTFILES/zsh/aliases
. $DOTFILES/zsh/opts
. $DOTFILES/zsh/oh-my-zsh

# History
HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/.zsh_history
HIST_STAMPS="dd/mm/yyyy"

# load powerline10k config, previously configured
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Include local settings
[[ -f ~/.zshrc.local ]] && . ~/.zshrc.local