name: Smoke Test CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Execute full install
      run: |
        chmod +x "${GITHUB_WORKSPACE}/install.sh"
        "${GITHUB_WORKSPACE}/install.sh"
